name: mvp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for making http requests to servers
  http: ^0.12.1
  # firebase realtime database for shopping cart
  cloud_firestore: ^0.13.6
  # for state management across the app
  provider: ^4.1.2
  # google maps for location
  google_maps_flutter: ^0.5.28+1
  # for showing toasts
  fluttertoast: ^4.0.1
  # shared prefs for storing user values on device
  shared_preferences: ^0.5.7+3
  # for caching images and not hit urls
  cached_network_image: ^2.2.0+1
  # online payments
  razorpay_flutter: ^1.2.1
  # for otp login field
  otp_text_field: ^1.0.1
  # firebase messaging - notifs
  firebase_messaging: ^6.0.16
  # for location
  location: ^3.0.0
  # for gridview
  flutter_staggered_grid_view: "^0.3.1"
  # for getting locations address from lat/long
  geocoder: ^0.2.1
  # For otp fields
  pin_code_text_field: ^1.7.1
  # shimmer view - loading
  shimmer: ^1.1.1
  # for featured cards
  carousel_slider: ^2.2.1
  # for launching urls
  url_launcher: ^5.6.0
  # sharing app
  share: ^0.6.5+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # splash screen
  flutter_native_splash: ^0.1.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  image: images/seva.png
  color: "ffffff"
  fill: true
